services:

  app:
    build: .
    container_name: laravel_app
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: "base64:eZ/bltVtghoaZSdU+I14iF/BKOXCgnenDnmO2UCu+fk="
      APP_URL: http://localhost:8000
    volumes:
      - vendor_data:/var/www/vendor
      # - storage_data:/var/www/storage
      - /var/www/test_apps:/var/www/storage/app/public
      # - C:\Users\tennu\Documents\RND\Laravel:/var/www/storage/app/public
      - cache_data:/var/www/bootstrap/cache
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: laravel_nginx
    ports:
      - "8081:80"
    volumes:
      # - storage_data:/var/www/storage:ro
      - /var/www/test_apps:/var/www/storage/app/public:ro
      # - C:\Users\tennu\Documents\RND\Laravel:/var/www/storage/app/public:ro
      - cache_data:/var/www/bootstrap/cache:ro
    depends_on:
      app:
        condition: service_healthy
    networks:
      - laravel

networks:
  laravel:

volumes:
  # storage_data:
  cache_data:
  vendor_data:
